import owlready2 as or2

onto = or2.get_ontology("mlprov.owx").load()

req_spec = onto["requirement_specification"]
train_data = onto["training_dataset"]
test_data = onto["testing_dataset"]
map = onto["performance_metric"]


with onto:
    class description(or2.DataProperty):
        range = [str]

req1 = req_spec("req1")
req1.description = ["The model shall detect instances of the 'person' class within images."]
req2 = req_spec("req2")
req2.description = ["The model shall detect instances of the 'bicycle' class within images."]
req3 = req_spec("req3")
req3.description = ["The model shall detect instances of the 'car' class within images."]
req4 = req_spec("req4")
req4.description = ["The model shall detect instances of the 'motorcycle' class within images."]
req5 = req_spec("req5")
req5.description = ["The model shall detect instances of the 'airplane' class within images."]
req6 = req_spec("req6")
req6.description = ["The model shall detect instances of the 'bus' class within images."]
req7 = req_spec("req7")
req7.description = ["The model shall detect instances of the 'train' class within images."]
req8 = req_spec("req8")
req8.description = ["The model shall detect instances of the 'truck' class within images."]
req9 = req_spec("req9")
req9.description = ["The model shall detect instances of the 'boat' class within images."]
req10 = req_spec("req10")
req10.description = ["The model shall detect instances of the 'traffic light' class within images."]
req11 = req_spec("req11")
req11.description = ["The model shall detect instances of the 'fire hydrant' class within images."]
req12 = req_spec("req12")
req12.description = ["The model shall detect instances of the 'stop sign' class within images."]
req13 = req_spec("req13")
req13.description = ["The model shall detect instances of the 'parking meter' class within images."]
req14 = req_spec("req14")
req14.description = ["The model shall detect instances of the 'bench' class within images."]
req15 = req_spec("req15")
req15.description = ["The model shall detect instances of the 'bird' class within images."]
req16 = req_spec("req16")
req16.description = ["The model shall detect instances of the 'cat' class within images."]
req17 = req_spec("req17")
req17.description = ["The model shall detect instances of the 'dog' class within images."]
req18 = req_spec("req18")
req18.description = ["The model shall detect instances of the 'horse' class within images."]
req19 = req_spec("req19")
req19.description = ["The model shall detect instances of the 'sheep' class within images."]
req20 = req_spec("req20")
req20.description = ["The model shall detect instances of the 'cow' class within images."]
req21 = req_spec("req21")
req21.description = ["The model shall detect instances of the 'elephant' class within images."]
req22 = req_spec("req22")
req22.description = ["The model shall detect instances of the 'bear' class within images."]
req23 = req_spec("req23")
req23.description = ["The model shall detect instances of the 'zebra' class within images."]
req24 = req_spec("req24")
req24.description = ["The model shall detect instances of the 'giraffe' class within images."]
req25 = req_spec("req25")
req25.description = ["The model shall detect instances of the 'backpack' class within images."]
req26 = req_spec("req26")
req26.description = ["The model shall detect instances of the 'umbrella' class within images."]
req27 = req_spec("req27")
req27.description = ["The model shall detect instances of the 'handbag' class within images."]
req28 = req_spec("req28")
req28.description = ["The model shall detect instances of the 'tie' class within images."]
req29 = req_spec("req29")
req29.description = ["The model shall detect instances of the 'suitcase' class within images."]
req30 = req_spec("req30")
req30.description = ["The model shall detect instances of the 'frisbee' class within images."]
req31 = req_spec("req31")
req31.description = ["The model shall detect instances of the 'skis' class within images."]
req32 = req_spec("req32")
req32.description = ["The model shall detect instances of the 'snowboard' class within images."]
req33 = req_spec("req33")
req33.description = ["The model shall detect instances of the 'sports ball' class within images."]
req34 = req_spec("req34")
req34.description = ["The model shall detect instances of the 'kite' class within images."]
req35= req_spec("req35")
req35.description = ["The model shall detect instances of the 'baseball bat' class within images."]
req36 = req_spec("req36")
req36.description = ["The model shall detect instances of the 'baseball glove' class within images."]
req37 = req_spec("req37")
req37.description = ["The model shall detect instances of the 'skateboard' class within images."]
req38 = req_spec("req38")
req38.description = ["The model shall detect instances of the 'surfboard' class within images."]
req39 = req_spec("req39")
req39.description = ["The model shall detect instances of the 'tennis racket' class within images."]
req40 = req_spec("req40")
req40.description = ["The model shall detect instances of the 'bottle' class within images."]
req41 = req_spec("req41")
req41.description = ["The model shall detect instances of the 'wine glass' class within images."]
req42 = req_spec("req42")
req42.description = ["The model shall detect instances of the 'cup' class within images."]
req43 = req_spec("req43")
req43.description = ["The model shall detect instances of the 'fork' class within images."]
req44 = req_spec("req44")
req44.description = ["The model shall detect instances of the 'knife' class within images."]
req45 = req_spec("req45")
req45.description = ["The model shall detect instances of the 'spoon' class within images."]
req46 = req_spec("req46")
req46.description = ["The model shall detect instances of the 'bowl' class within images."]
req47 = req_spec("req47")
req47.description = ["The model shall detect instances of the 'banana' class within images."]
req48 = req_spec("req48")
req48.description = ["The model shall detect instances of the 'apple' class within images."]
req49 = req_spec("req49")
req49.description = ["The model shall detect instances of the 'sandwich' class within images."]
req50 = req_spec("req50")
req50.description = ["The model shall detect instances of the 'orange' class within images."]
req51 = req_spec("req51")
req51.description = ["The model shall detect instances of the 'broccoli' class within images."]
req52 = req_spec("req52")
req52.description = ["The model shall detect instances of the 'carrot' class within images."]
req53 = req_spec("req53")
req53.description = ["The model shall detect instances of the 'hot dog' class within images."]
req54 = req_spec("req54")
req54.description = ["The model shall detect instances of the 'pizza' class within images."]
req55 = req_spec("req55")
req55.description = ["The model shall detect instances of the 'donut' class within images."]
req56 = req_spec("req56")
req56.description = ["The model shall detect instances of the 'cake' class within images."]
req57 = req_spec("req57")
req57.description = ["The model shall detect instances of the 'chair' class within images."]
req58 = req_spec("req58")
req58.description = ["The model shall detect instances of the 'couch' class within images."]
req59 = req_spec("req59")
req59.description = ["The model shall detect instances of the 'potted plant' class within images."]
req60 = req_spec("req60")
req60.description = ["The model shall detect instances of the 'bed' class within images."]
req61 = req_spec("req61")
req61.description = ["The model shall detect instances of the 'dining table' class within images."]
req62 = req_spec("req62")
req62.description = ["The model shall detect instances of the 'toilet' class within images."]
req63 = req_spec("req63")
req63.description = ["The model shall detect instances of the 'tv' class within images."]
req64 = req_spec("req64")
req64.description = ["The model shall detect instances of the 'laptop' class within images."]
req65 = req_spec("req65")
req65.description = ["The model shall detect instances of the 'mouse' class within images."]
req66 = req_spec("req66")
req66.description = ["The model shall detect instances of the 'remote' class within images."]
req67 = req_spec("req67")
req67.description = ["The model shall detect instances of the 'keyboard' class within images."]
req68 = req_spec("req68")
req68.description = ["The model shall detect instances of the 'cell phone' class within images."]
req69 = req_spec("req69")
req69.description = ["The model shall detect instances of the 'microwave' class within images."]
req70 = req_spec("req70")
req70.description = ["The model shall detect instances of the 'oven' class within images."]
req71 = req_spec("req71")
req71.description = ["The model shall detect instances of the 'toaster' class within images."]
req72 = req_spec("req72")
req72.description = ["The model shall detect instances of the 'sink' class within images."]
req73 = req_spec("req73")
req73.description = ["The model shall detect instances of the 'refrigerator' class within images."]
req74 = req_spec("req74")
req74.description = ["The model shall detect instances of the 'book' class within images."]
req75 = req_spec("req75")
req75.description = ["The model shall detect instances of the 'clock' class within images."]
req76 = req_spec("req76")
req76.description = ["The model shall detect instances of the 'vase' class within images."]
req77 = req_spec("req77")
req77.description = ["The model shall detect instances of the 'scissors' class within images."]
req78 = req_spec("req78")
req78.description = ["The model shall detect instances of the 'teddy bear' class within images."]
req79 = req_spec("req79")
req79.description = ["The model shall detect instances of the 'hair drier' class within images."]
req80 = req_spec("req80")
req80.description = ["The model shall detect instances of the 'toothbrush' class within images."]


training_dataset = train_data("Training Dataset")
training_dataset.description = ["http://images.cocodataset.org/zips/train2017.zip"]
testing_dataset = test_data("Testing Dataset")
testing_dataset.description = ["http://images.cocodataset.org/zips/test2017.zip"]

yolov8_map = map("YOLOv8x mAP")
yolov8_map.description = ["53.9"]


onto.save(file="mlprov_ecp_instances.owl")